// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/shinnosuke-K/github-dev-insight/ent/commits"
	"github.com/shinnosuke-K/github-dev-insight/ent/predicate"
	"github.com/shinnosuke-K/github-dev-insight/ent/pullrequest"
	"github.com/shinnosuke-K/github-dev-insight/ent/repository"
)

// PullRequestQuery is the builder for querying PullRequest entities.
type PullRequestQuery struct {
	config
	ctx            *QueryContext
	order          []OrderFunc
	inters         []Interceptor
	predicates     []predicate.PullRequest
	withCommits    *CommitsQuery
	withRepository *RepositoryQuery
	withFKs        bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PullRequestQuery builder.
func (prq *PullRequestQuery) Where(ps ...predicate.PullRequest) *PullRequestQuery {
	prq.predicates = append(prq.predicates, ps...)
	return prq
}

// Limit the number of records to be returned by this query.
func (prq *PullRequestQuery) Limit(limit int) *PullRequestQuery {
	prq.ctx.Limit = &limit
	return prq
}

// Offset to start from.
func (prq *PullRequestQuery) Offset(offset int) *PullRequestQuery {
	prq.ctx.Offset = &offset
	return prq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (prq *PullRequestQuery) Unique(unique bool) *PullRequestQuery {
	prq.ctx.Unique = &unique
	return prq
}

// Order specifies how the records should be ordered.
func (prq *PullRequestQuery) Order(o ...OrderFunc) *PullRequestQuery {
	prq.order = append(prq.order, o...)
	return prq
}

// QueryCommits chains the current query on the "commits" edge.
func (prq *PullRequestQuery) QueryCommits() *CommitsQuery {
	query := (&CommitsClient{config: prq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := prq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := prq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pullrequest.Table, pullrequest.FieldID, selector),
			sqlgraph.To(commits.Table, commits.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, pullrequest.CommitsTable, pullrequest.CommitsColumn),
		)
		fromU = sqlgraph.SetNeighbors(prq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRepository chains the current query on the "repository" edge.
func (prq *PullRequestQuery) QueryRepository() *RepositoryQuery {
	query := (&RepositoryClient{config: prq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := prq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := prq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pullrequest.Table, pullrequest.FieldID, selector),
			sqlgraph.To(repository.Table, repository.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pullrequest.RepositoryTable, pullrequest.RepositoryColumn),
		)
		fromU = sqlgraph.SetNeighbors(prq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PullRequest entity from the query.
// Returns a *NotFoundError when no PullRequest was found.
func (prq *PullRequestQuery) First(ctx context.Context) (*PullRequest, error) {
	nodes, err := prq.Limit(1).All(setContextOp(ctx, prq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{pullrequest.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (prq *PullRequestQuery) FirstX(ctx context.Context) *PullRequest {
	node, err := prq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PullRequest ID from the query.
// Returns a *NotFoundError when no PullRequest ID was found.
func (prq *PullRequestQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = prq.Limit(1).IDs(setContextOp(ctx, prq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{pullrequest.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (prq *PullRequestQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := prq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PullRequest entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PullRequest entity is found.
// Returns a *NotFoundError when no PullRequest entities are found.
func (prq *PullRequestQuery) Only(ctx context.Context) (*PullRequest, error) {
	nodes, err := prq.Limit(2).All(setContextOp(ctx, prq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{pullrequest.Label}
	default:
		return nil, &NotSingularError{pullrequest.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (prq *PullRequestQuery) OnlyX(ctx context.Context) *PullRequest {
	node, err := prq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PullRequest ID in the query.
// Returns a *NotSingularError when more than one PullRequest ID is found.
// Returns a *NotFoundError when no entities are found.
func (prq *PullRequestQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = prq.Limit(2).IDs(setContextOp(ctx, prq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{pullrequest.Label}
	default:
		err = &NotSingularError{pullrequest.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (prq *PullRequestQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := prq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PullRequests.
func (prq *PullRequestQuery) All(ctx context.Context) ([]*PullRequest, error) {
	ctx = setContextOp(ctx, prq.ctx, "All")
	if err := prq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PullRequest, *PullRequestQuery]()
	return withInterceptors[[]*PullRequest](ctx, prq, qr, prq.inters)
}

// AllX is like All, but panics if an error occurs.
func (prq *PullRequestQuery) AllX(ctx context.Context) []*PullRequest {
	nodes, err := prq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PullRequest IDs.
func (prq *PullRequestQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if prq.ctx.Unique == nil && prq.path != nil {
		prq.Unique(true)
	}
	ctx = setContextOp(ctx, prq.ctx, "IDs")
	if err = prq.Select(pullrequest.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (prq *PullRequestQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := prq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (prq *PullRequestQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, prq.ctx, "Count")
	if err := prq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, prq, querierCount[*PullRequestQuery](), prq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (prq *PullRequestQuery) CountX(ctx context.Context) int {
	count, err := prq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (prq *PullRequestQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, prq.ctx, "Exist")
	switch _, err := prq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (prq *PullRequestQuery) ExistX(ctx context.Context) bool {
	exist, err := prq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PullRequestQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (prq *PullRequestQuery) Clone() *PullRequestQuery {
	if prq == nil {
		return nil
	}
	return &PullRequestQuery{
		config:         prq.config,
		ctx:            prq.ctx.Clone(),
		order:          append([]OrderFunc{}, prq.order...),
		inters:         append([]Interceptor{}, prq.inters...),
		predicates:     append([]predicate.PullRequest{}, prq.predicates...),
		withCommits:    prq.withCommits.Clone(),
		withRepository: prq.withRepository.Clone(),
		// clone intermediate query.
		sql:  prq.sql.Clone(),
		path: prq.path,
	}
}

// WithCommits tells the query-builder to eager-load the nodes that are connected to
// the "commits" edge. The optional arguments are used to configure the query builder of the edge.
func (prq *PullRequestQuery) WithCommits(opts ...func(*CommitsQuery)) *PullRequestQuery {
	query := (&CommitsClient{config: prq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	prq.withCommits = query
	return prq
}

// WithRepository tells the query-builder to eager-load the nodes that are connected to
// the "repository" edge. The optional arguments are used to configure the query builder of the edge.
func (prq *PullRequestQuery) WithRepository(opts ...func(*RepositoryQuery)) *PullRequestQuery {
	query := (&RepositoryClient{config: prq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	prq.withRepository = query
	return prq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		GithubID string `json:"github_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PullRequest.Query().
//		GroupBy(pullrequest.FieldGithubID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (prq *PullRequestQuery) GroupBy(field string, fields ...string) *PullRequestGroupBy {
	prq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PullRequestGroupBy{build: prq}
	grbuild.flds = &prq.ctx.Fields
	grbuild.label = pullrequest.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		GithubID string `json:"github_id,omitempty"`
//	}
//
//	client.PullRequest.Query().
//		Select(pullrequest.FieldGithubID).
//		Scan(ctx, &v)
func (prq *PullRequestQuery) Select(fields ...string) *PullRequestSelect {
	prq.ctx.Fields = append(prq.ctx.Fields, fields...)
	sbuild := &PullRequestSelect{PullRequestQuery: prq}
	sbuild.label = pullrequest.Label
	sbuild.flds, sbuild.scan = &prq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PullRequestSelect configured with the given aggregations.
func (prq *PullRequestQuery) Aggregate(fns ...AggregateFunc) *PullRequestSelect {
	return prq.Select().Aggregate(fns...)
}

func (prq *PullRequestQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range prq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, prq); err != nil {
				return err
			}
		}
	}
	for _, f := range prq.ctx.Fields {
		if !pullrequest.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if prq.path != nil {
		prev, err := prq.path(ctx)
		if err != nil {
			return err
		}
		prq.sql = prev
	}
	return nil
}

func (prq *PullRequestQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PullRequest, error) {
	var (
		nodes       = []*PullRequest{}
		withFKs     = prq.withFKs
		_spec       = prq.querySpec()
		loadedTypes = [2]bool{
			prq.withCommits != nil,
			prq.withRepository != nil,
		}
	)
	if prq.withRepository != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, pullrequest.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PullRequest).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PullRequest{config: prq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, prq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := prq.withCommits; query != nil {
		if err := prq.loadCommits(ctx, query, nodes,
			func(n *PullRequest) { n.Edges.Commits = []*Commits{} },
			func(n *PullRequest, e *Commits) { n.Edges.Commits = append(n.Edges.Commits, e) }); err != nil {
			return nil, err
		}
	}
	if query := prq.withRepository; query != nil {
		if err := prq.loadRepository(ctx, query, nodes, nil,
			func(n *PullRequest, e *Repository) { n.Edges.Repository = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (prq *PullRequestQuery) loadCommits(ctx context.Context, query *CommitsQuery, nodes []*PullRequest, init func(*PullRequest), assign func(*PullRequest, *Commits)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*PullRequest)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Commits(func(s *sql.Selector) {
		s.Where(sql.InValues(pullrequest.CommitsColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.pull_request_id
		if fk == nil {
			return fmt.Errorf(`foreign-key "pull_request_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "pull_request_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (prq *PullRequestQuery) loadRepository(ctx context.Context, query *RepositoryQuery, nodes []*PullRequest, init func(*PullRequest), assign func(*PullRequest, *Repository)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*PullRequest)
	for i := range nodes {
		if nodes[i].repository_id == nil {
			continue
		}
		fk := *nodes[i].repository_id
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(repository.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "repository_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (prq *PullRequestQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := prq.querySpec()
	_spec.Node.Columns = prq.ctx.Fields
	if len(prq.ctx.Fields) > 0 {
		_spec.Unique = prq.ctx.Unique != nil && *prq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, prq.driver, _spec)
}

func (prq *PullRequestQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(pullrequest.Table, pullrequest.Columns, sqlgraph.NewFieldSpec(pullrequest.FieldID, field.TypeUUID))
	_spec.From = prq.sql
	if unique := prq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if prq.path != nil {
		_spec.Unique = true
	}
	if fields := prq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pullrequest.FieldID)
		for i := range fields {
			if fields[i] != pullrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := prq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := prq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := prq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := prq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (prq *PullRequestQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(prq.driver.Dialect())
	t1 := builder.Table(pullrequest.Table)
	columns := prq.ctx.Fields
	if len(columns) == 0 {
		columns = pullrequest.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if prq.sql != nil {
		selector = prq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if prq.ctx.Unique != nil && *prq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range prq.predicates {
		p(selector)
	}
	for _, p := range prq.order {
		p(selector)
	}
	if offset := prq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := prq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PullRequestGroupBy is the group-by builder for PullRequest entities.
type PullRequestGroupBy struct {
	selector
	build *PullRequestQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (prgb *PullRequestGroupBy) Aggregate(fns ...AggregateFunc) *PullRequestGroupBy {
	prgb.fns = append(prgb.fns, fns...)
	return prgb
}

// Scan applies the selector query and scans the result into the given value.
func (prgb *PullRequestGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, prgb.build.ctx, "GroupBy")
	if err := prgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PullRequestQuery, *PullRequestGroupBy](ctx, prgb.build, prgb, prgb.build.inters, v)
}

func (prgb *PullRequestGroupBy) sqlScan(ctx context.Context, root *PullRequestQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(prgb.fns))
	for _, fn := range prgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*prgb.flds)+len(prgb.fns))
		for _, f := range *prgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*prgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := prgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PullRequestSelect is the builder for selecting fields of PullRequest entities.
type PullRequestSelect struct {
	*PullRequestQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (prs *PullRequestSelect) Aggregate(fns ...AggregateFunc) *PullRequestSelect {
	prs.fns = append(prs.fns, fns...)
	return prs
}

// Scan applies the selector query and scans the result into the given value.
func (prs *PullRequestSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, prs.ctx, "Select")
	if err := prs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PullRequestQuery, *PullRequestSelect](ctx, prs.PullRequestQuery, prs, prs.inters, v)
}

func (prs *PullRequestSelect) sqlScan(ctx context.Context, root *PullRequestQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(prs.fns))
	for _, fn := range prs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*prs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := prs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
