name: dependabot-random-reviewers

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && vars.REVIEWERS != ''
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Select a random reviewer
        env:
          REVIEWERS: ${{ vars.REVIEWERS }}
        run: |
          RANDOM_REVIEWER=$(echo "$REVIEWERS" | tr ',' '\n' | shuf -n 1)
          echo "Selected reviewer: $RANDOM_REVIEWER"
          echo "REVIEWER=$RANDOM_REVIEWER" >> $GITHUB_ENV

      - name: Assign reviewer
        run: gh pr edit ${{ github.event.pull_request.number }} --add-reviewer $REVIEWER
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
