name: dependabot-random-reviewers

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && vars.REVIEWERS != ''
    steps:
      - name: Select a random reviewer from environment variable
        env:
          REVIEWERS: ${{ vars.REVIEWERS }}  # GitHub Actionsのリポジトリ変数から取得
        run: |
          RANDOM_REVIEWER=$(echo "$REVIEWERS" | tr ',' '\n' | shuf -n 1)
          echo "REVIEWER=$RANDOM_REVIEWER" >> $GITHUB_ENV

      - name: Assign reviewer
        run: gh pr edit ${{ github.event.pull_request.number }} --add-reviewer $REVIEWER
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
