// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Commits is the predicate function for commits builders.
type Commits func(*sql.Selector)

// Issue is the predicate function for issue builders.
type Issue func(*sql.Selector)

// PullRequest is the predicate function for pullrequest builders.
type PullRequest func(*sql.Selector)

// Repository is the predicate function for repository builders.
type Repository func(*sql.Selector)
